"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabaseClient";

type OpeningHour = { dayOfWeek: number; isOpen: boolean; openTime: string; closeTime: string; breakStart: string | null; breakEnd: string | null; };
type BusySlot = { startTime: string; endTime: string; };
type BlockedPeriod = { startDate: string; endDate: string; startTime: string | null; endTime: string | null; };
function dateKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function dateFromKey(key: string) { return new Date(`${key}T12:00:00`); }
function getMinutes(time: string) { const [hours, minutes] = time.split(":").map(Number); return hours * 60 + minutes; }
function getEndTime(start: string, duration: number) { const [hours, minutes] = start.split(":").map(Number); const end = new Date(2000, 0, 1, hours, minutes + duration); return `${String(end.getHours()).padStart(2, "0")}:${String(end.getMinutes()).padStart(2, "0")}`; }
function daysForMonth(month: Date) { const first = new Date(month.getFullYear(), month.getMonth(), 1); const offset = first.getDay(); const total = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); return [...Array(offset).fill(null), ...Array.from({ length: total }, (_, index) => new Date(month.getFullYear(), month.getMonth(), index + 1))]; }

export function ChangeRequestPicker({ token, durationMinutes, onSubmitted }: { token: string; durationMinutes: number; onSubmitted: () => void }) {
  const now = new Date(); const earliestChange = new Date(now.getTime() + 24 * 60 * 60 * 1000); const minDate = dateKey(earliestChange); const monday = new Date(now.getFullYear(), now.getMonth(), now.getDate() - ((now.getDay() + 6) % 7)); const maxDate = dateKey(new Date(monday.getFullYear(), monday.getMonth(), monday.getDate() + 20));
  const [openingHours, setOpeningHours] = useState<OpeningHour[]>([]); const [blockedPeriods, setBlockedPeriods] = useState<BlockedPeriod[]>([]); const [monthAvailability, setMonthAvailability] = useState<Record<string, boolean>>({}); const [bookingDate, setBookingDate] = useState(""); const [startTime, setStartTime] = useState(""); const [calendarMonth, setCalendarMonth] = useState(new Date(now.getFullYear(), now.getMonth(), 1)); const [errorMessage, setErrorMessage] = useState(""); const [isSubmitting, setIsSubmitting] = useState(false);
  const openingHour = bookingDate ? openingHours.find((hours) => hours.dayOfWeek === dateFromKey(bookingDate).getDay()) : null;
  const isFullyBlocked = (date: Date) => { const key = dateKey(date); return blockedPeriods.some((period) => key >= period.startDate && key <= period.endDate && !period.startTime && !period.endTime); };
  function timeOptions(date: string, hours: OpeningHour, busySlots: BusySlot[]) { const periods = blockedPeriods.filter((period) => date >= period.startDate && date <= period.endDate); const options: string[] = []; for (let minutes = getMinutes(hours.openTime); minutes + durationMinutes <= getMinutes(hours.closeTime); minutes += 30) { const start = `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`; const end = getEndTime(start, durationMinutes); const tooSoon = new Date(`${date}T${start}:00`).getTime() < Date.now() + 24 * 60 * 60 * 1000; const breakConflict = hours.breakStart && hours.breakEnd && getMinutes(start) < getMinutes(hours.breakEnd) && getMinutes(end) > getMinutes(hours.breakStart); const timeOffConflict = periods.some((period) => !period.startTime || !period.endTime || (getMinutes(start) < getMinutes(period.endTime) && getMinutes(end) > getMinutes(period.startTime))); const bookingConflict = busySlots.some((slot) => getMinutes(start) < getMinutes(slot.endTime) && getMinutes(end) > getMinutes(slot.startTime)); if (!tooSoon && !breakConflict && !timeOffConflict && !bookingConflict) options.push(start); } return options; }
  const selectedTimes = useMemo(() => openingHour?.isOpen && bookingDate ? timeOptions(bookingDate, openingHour, []) : [], [openingHour, bookingDate, durationMinutes, blockedPeriods]);
  useEffect(() => { async function loadSetup() { if (!supabase) return; const [{ data: hours }, { data: periods }] = await Promise.all([supabase.from("opening_hours").select("dayOfWeek, isOpen, openTime, closeTime, breakStart, breakEnd"), supabase.from("blocked_periods").select("startDate, endDate, startTime, endTime")]); setOpeningHours((hours ?? []) as OpeningHour[]); setBlockedPeriods((periods ?? []) as BlockedPeriod[]); } void loadSetup(); }, []);
  useEffect(() => { async function loadAvailability() { if (!supabase || !openingHours.length) return; const dates = daysForMonth(calendarMonth).filter((date): date is Date => Boolean(date) && dateKey(date) >= minDate && dateKey(date) <= maxDate); const results = await Promise.all(dates.map(async (date) => { const key = dateKey(date); const hours = openingHours.find((item) => item.dayOfWeek === date.getDay()); if (!hours?.isOpen || isFullyBlocked(date)) return [key, false] as const; const { data } = await supabase.rpc("get_booked_times", { target_date: key }); return [key, timeOptions(key, hours, (data ?? []) as BusySlot[]).length > 0] as const; })); setMonthAvailability(Object.fromEntries(results)); } void loadAvailability(); }, [calendarMonth, openingHours, blockedPeriods, durationMinutes, minDate, maxDate]);
  async function submitRequest() { if (!supabase || !bookingDate || !startTime) return; setIsSubmitting(true); setErrorMessage(""); const [tokenHashBuffer] = await Promise.all([crypto.subtle.digest("SHA-256", new TextEncoder().encode(token))]); const tokenHash = Array.from(new Uint8Array(tokenHashBuffer)).map((byte) => byte.toString(16).padStart(2, "0")).join(""); const { error } = await supabase.rpc("request_booking_change_by_manage_token", { token_hash: tokenHash, requested_date: bookingDate, requested_start: startTime, requested_end: getEndTime(startTime, durationMinutes) }); if (error) setErrorMessage(error.message); else onSubmitted(); setIsSubmitting(false); }
  const days = daysForMonth(calendarMonth); const isAvailable = (date: Date) => { const key = dateKey(date); return key >= minDate && key <= maxDate && !isFullyBlocked(date) && openingHours.find((hours) => hours.dayOfWeek === date.getDay())?.isOpen && monthAvailability[key] !== false; };
  return <div className="change-request-picker"><div className="change-request-layout"><div className="date-picker-field"><span className="field-label">Date</span><div className="calendar"><div className="calendar-header"><button type="button" aria-label="Previous month" disabled={calendarMonth.getFullYear() === dateFromKey(minDate).getFullYear() && calendarMonth.getMonth() === dateFromKey(minDate).getMonth()} onClick={() => setCalendarMonth(new Date(calendarMonth.getFullYear(), calendarMonth.getMonth() - 1, 1))}>‹</button><strong>{calendarMonth.toLocaleDateString("en-GB", { month: "long", year: "numeric" })}</strong><button type="button" aria-label="Next month" disabled={calendarMonth.getFullYear() > dateFromKey(maxDate).getFullYear() || (calendarMonth.getFullYear() === dateFromKey(maxDate).getFullYear() && calendarMonth.getMonth() >= dateFromKey(maxDate).getMonth())} onClick={() => setCalendarMonth(new Date(calendarMonth.getFullYear(), calendarMonth.getMonth() + 1, 1))}>›</button></div><div className="calendar-weekdays">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{days.map((date, index) => date ? <button type="button" key={dateKey(date)} className={`${bookingDate === dateKey(date) ? "selected" : ""}${isAvailable(date) ? "" : " unavailable"}`} disabled={!isAvailable(date)} onClick={() => { setBookingDate(dateKey(date)); setStartTime(""); }} aria-label={date.toDateString()}>{date.getDate()}</button> : <span className="calendar-empty" key={`empty-${index}`} />)}</div><p className="selected-date">{bookingDate ? dateFromKey(bookingDate).toLocaleDateString("en-GB", { weekday: "short", day: "numeric", month: "short" }) : "Choose a date"}</p></div></div><div className="time-picker-field"><span className="field-label">Time</span><div className="time-picker">{!bookingDate ? <p className="picker-placeholder">Choose a date first</p> : selectedTimes.length ? <div className="time-options">{selectedTimes.map((time) => <button type="button" key={time} className={startTime === time ? "selected" : ""} onClick={() => setStartTime(time)}>{time}</button>)}</div> : <p className="picker-placeholder">No times available</p>}</div></div></div>{errorMessage && <p className="form-error">{errorMessage}</p>}<button className="button button-dark" type="button" onClick={() => void submitRequest()} disabled={!bookingDate || !startTime || isSubmitting}>{isSubmitting ? "Sending request…" : "Send change request ↗"}</button></div>;
}
